language: node_js
node_js: "12"

services: mongod
addons:
  apt:
    sources:
      - sourceline: 'deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse'
        key_url: 'https://www.mongodb.org/static/pgp/server-4.2.asc'
    packages:
      - mongodb-org
      - mongodb-org-server
      - mongodb-org-shell
      - mongodb-org-mongos
      - mongodb-org-tools

env:
  - MODE=test

before_install:
  - mongo --version
  - mongod --version
  - |
    mongo admin --eval 'db.createUser(
        {
          user: "admin",
          pwd: "password",
          roles: [ 
            { role: "userAdminAnyDatabase", db: "admin" }, 
            "readWriteAnyDatabase"
          ]
        }
      )'
  - |
    mongo codematch --eval 'db.createUser(
      {
        user: "codematch",
        pwd: "password",
        roles: [ "dbOwner" ]
      }
    )'
  - cp config.js.example config.js

script:
  - npm test
  - npm run lint
