language: node_js
node_js: "12"

services: mongodb

env:
  - MODE=test

before_install:
  - |
    mongo admin --eval 'db.createUser(
        {
          user: "admin",
          pwd: "password",
          roles: [ 
            { role: "userAdminAnyDatabase", db: "admin" }, 
            "readWriteAnyDatabase"
          ]
        }
      )'
  - |
    mongo codematch --eval 'db.createUser(
      {
        user: "codematch",
        pwd: "password",
        roles: [ "dbOwner" ]
      }
    )'
  - cp config.js.example config.js
  - mongorestore --db=codematch --username=codematch --password=password data/tests/dump/codematch

script:
  - npm test
  - npm run lint
